version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: pusher/pusher-php-server
    versions:
    - 6.0.1
